version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "9000:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9001:9001"
    env_file:
      - ./server/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

networks:
  default:
    driver: bridge
